package packMain;

//EL COMPILADOR NECESITA UNA CLASE MAIN QUE NO EXTIENDA DE NINGUNA OTRA
//POR ESO SE HA CREADO ESTA CLASE QUE LLAMA AL MAIN DE VERDAD
//LA CREACIÓN DEL JAR SE HA PROBADO CON JAVA 11
//SE HA AÑADIDO EL PLUGIN SHADE, EL CUAL SE EJECUTA AL EJECUTAR MVN INSTALL
//LOS JARS SE CREAN CON MAVEN INSTALL EN TARGET/*.JAR
//LOS TESTS SE SALTAN
//SI SE USA JAVA 11, PARA EJECUTAR EN EL IDE:
//      1. MAVEN -> PLUGINS -> JAVAFX -> JAVAFX:RUN
//      2. EJECUTAR NEWMAIN
//SI NO APARECE MAVEN -> RECOMPILE (CLICK DERECHO EN EL POM)
//SE PUEDEN USAR DOS JDK PARA EJECUTAR EL PROYECTO:
//  - JRE1.8.0_181 -> YA QUE TIENE JFXRT.JAR Y LO HACE COMPATIBLE CON JAVAFX
//  (PARA CUALQUIER OTRA VERSIÓN COMPIAR EL JFXRT.JAR EN EL JRE)
//  - A PARTIR DE JAVA 11 -> YA QUE JAVAFX ES COMPATIBLE CON ESTAS NUEVAS VERSIONES

public class NewMain {

    public static void main(String[] args) {
        Main.main(args);
    }
}
